In [12]:
import numpy as np
a=np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [14]:
a.shape

(20,)

In [17]:
a[5]

5

In [19]:
#creating two dimensional array
x=np.arange(20).reshape(2,10)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [21]:
x=np.arange(50).reshape(5,10)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [22]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.empty((6,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.33511018e-306, 7.56599807e-307, 1.42418987e-306],
       [1.37961641e-306, 1.60220528e-306, 1.24611266e-306],
       [9.34598925e-307, 1.24612081e-306, 1.11260755e-306],
       [1.60220393e-306, 1.51320640e-306, 9.34609790e-307],
       [1.86921279e-306, 1.24610723e-306, 0.00000000e+000]])

In [29]:
np.full((3,3),4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [31]:
np.eye(7,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [38]:
np.linspace(0,10,num=6)

array([ 0.,  2.,  4.,  6.,  8., 10.])