In [5]:
import numpy as np
x=np.arange(10)
print(x)
x.shape


[0 1 2 3 4 5 6 7 8 9]


(10,)

In [4]:
import numpy as np
x=np.arange(15).reshape(3,5)
x


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
x=np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
x=np.ones((4,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
x=np.empty((2,3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.empty((5,2))


array([[2.12199579e-314, 6.36598737e-314],
       [1.06099790e-313, 1.48539705e-313],
       [1.90979621e-313, 2.33419537e-313],
       [2.75859453e-313, 3.18299369e-313],
       [3.60739285e-313, 4.03179200e-313]])

In [18]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [21]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [27]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.eye(3,3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])