In [3]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.22.4
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

In [4]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [12]:
import numpy as np
np.info(np.add)
x1=np.arange(9).reshape((3,3))
x2=np.arange(9)
np.add(x1+x2)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

ValueError: operands could not be broadcast together with shapes (3,3) (9,) 

In [16]:
#To test whether none of the elements of the given array is zero
#true
import numpy as np
x=np.array([1,2,3,4,5])
print("original array:")
print(x)
print("test if none of the element of the array is zero:")
print(np.all(x))
#for false
import numpy as np
a=np.array([0,1,2,0])
print("original array")
print(a)
print("Test None of the element in the array is zero ")
print(np.all(a))

original array:
[1 2 3 4 5]
test if none of the element of the array is zero:
True
original array
[0 1 2 0]
None of the element in the array is zero 
False


In [21]:
#To test if any of the elements of a given array is non-zero
#any() for true
import numpy as np
a=np.array([1,2,3,4,5])
print("original array")
print(a)
print("test if one any of the element in the array is non-zero")
print(np.any(a))
#any() for false
import numpy as np
a=np.array([0,0,0,0])
print("original array")
print(a)
print("test if one any of the element in the array is non-zero")
print(np.any(a))

original array
[1 2 3 4 5]
test if one any of the element in the array is zero
True
original array
[0 0 0 0]
test if one any of the element in the array is zero
False


In [24]:
#to test a given array element-wise finiteness(not infinity or not a number)
import numpy as np
a=np.array([0,1,2,np.inf,np.nan])
print("original array")
print(a)
print("test given array is element-wise finiteness")
print(np.isfinite(a))


original array
[ 0.  1.  2. inf nan]
test given array is element-wise finiteness
[ True  True  True False False]


In [33]:
#test element-wise for positive or negative or infinity
import numpy as np
a=np.array([1,np.nan,np.inf])
print("original array")
print(a)
print("Test whther a number is element-wise for positive or negative or infinity")
print(np.isinf(a))

original array
[ 1. nan inf]
Test whther a number is element-wise for positive or negative or infinity
[False False  True]


In [34]:
#to test element-wise for NAN of a given array
import numpy as np
a=([1,3,-2,np.inf,np.nan])
print(a)
print("To test element-wise for nan of given number")
print(np.isnan(a))

[1, 3, -2, inf, nan]
To test element-wise for nan of given number
[False False False False  True]


In [10]:
#test element-wise for complex number real number of a given array.Also test whether a given number is a scalar type or not
import numpy as np
a=np.array([1+2j,9+3j,3.1,9.8])
print("original array")
print(a)
print(np.iscomplex(a))
print("original array")
print(a)
print(np.isreal(a))
print("checking scalar type")
print(np.isscalar((a)))
print(np.isscalar((3)))

original array
[1. +2.j 9. +3.j 3.1+0.j 9.8+0.j]
[ True  True False False]
original array
[1. +2.j 9. +3.j 3.1+0.j 9.8+0.j]
[False False  True  True]
checking scalar type
False
True


In [14]:
#Whether two arrays are element-wise equal within a tolerance
import numpy as np
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7],[1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8],[1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8],[1.0001e10,1e-9]))
print(np.allclose([1.0,np.nan],[1.0,np.nan]))
print(np.allclose([1.0,np.nan],[1.0,np.nan],equal_nan=True))

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


In [1]:
#Create an element-wise comparison (greater,greater_equal,less and less_equal)of two given arrays
import numpy as np
x=np.array([3,5])
y=np.array([2,5])
print("original array")
print(x)
print(y)
print("Comparison-greater")
print(np.greater(x,y))
print("comparison-greater_equal")
print(np.greater_equal(x,y))
print("comparison-less")
print(np.less(x,y))
print("comparison-less_equal")
print(np.less_equal(x,y))

original array
[3 5]
[2 5]
Comparison-greater
[ True False]
comparison-greater_equal
[ True  True]
comparison-less
[False False]
comparison-less_equal
[False  True]


In [2]:
#Bumpy program to create an element-wise comparison (equal,equal within a tolerance)of two given arrays
import numpy as np
a=np.array([10,24,65,90,190,-130,120,-10,60,100])
b=np.array([10,24,65,90,190,-130,120,-10,60,100])
print("original array:")
print(a)
print(b)
print("comparison-equal:")
print(np.equal(a,b))
print("comparison -equal within a tolerance:")
print(np.allclose(a,b))

original array:
[  10   24   65   90  190 -130  120  -10   60  100]
[  10   24   65   90  190 -130  120  -10   60  100]
comparison-equal:
[ True  True  True  True  True  True  True  True  True  True]
comparison -equal within a tolerance:
True


In [5]:
#create an array with the values 1,7,13,105 and determine the size of the memory occupied by the array
import numpy as np
a=np.array([1,7,13,105])
print("original array")
print(a)
print("The size of the memory occupied by the array")
print("%d bytes"%(a.size *a.itemsize))

original array
[ 1  7 13]
The size of the memory occupied by the array
12 bytes


In [7]:
#Create an array of 10Zeros,10ones,10fives
import numpy as np
a=np.zeros(10)
print("The array having 10 zeros")
print(a)
a=np.ones(10)
print("The array having 10 ones")
print(a)
a=np.ones(10)*5
print("The array having 10 fives")
print(a)

The array having 10 zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
The array having 10 ones
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
The array having 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [9]:
#Create an array of the integers from 30 to 70
import numpy as np
a=np.arange(30,71)
print("The integers from 30 to 70:")
print(a)

The integers from 30 to 70:
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [14]:
#Create an array of all the even integers from 30 to 70
import numpy as np
a=np.arange(30,71,2)
print("The even integers from 30 to 70 are:")
print(a)
#Create an array of all the odd integers from 30 to 70
import numpy as np
a=np.arange(31,71,2)
print("The odd numbers from 30 to 70 are:")
print(a)

The even integers from 30 to 70 are:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
The odd numbers from 30 to 70 are:
[31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69]


In [19]:
#Create a 3x3 identity matrix
import numpy as np
a=np.identity(3)
print("The 3x3 identity matrix is:")
print(a)
a=np.identity(4)
print("The 4x4 identity matrix is:")
print(a)

The 3x3 identity matrix is:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
The 4x4 identity matrix is:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
#Generate a random number between 0 and 1
import numpy as np
a=np.random.normal(0,1,1)
print("A random number between o and 1")
print(a)

A random number between o and 1
[0.11150972]


In [26]:
#Generate an array of 15 random numbers from a standard normal distribution
import numpy as np
a=np.random.normal(0,1,15)
print("15 random numbers from a standard distribution ")
print(a)

15 random numbers from a standard distribution 
[ 0.02089601 -0.47297995  0.08504947 -0.30501743 -1.54480561 -0.93735489
  0.65611776 -0.10315891 -0.74510126 -2.2778755   0.34483332 -0.27432442
  0.46234587  0.42181262 -1.62810741]


In [28]:
#create a vector with values ranging from 15 to 55 and print all values except the first and last
import numpy as np
v=np.arange(15,55)
print("original vector:")
print(v)
print("all values except the first and last:")
print(v[1:-1])

original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
all values except the first and last:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [3]:
#create a 3x4 array using and iterate over it
import numpy as np
a=np.arange(10,22).reshape((3,4))
print("original array")
print(a)
print("each element of the array is:")
for i in np.nditer(a):
    print(i,end=" ")

original array
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

In [2]:
#Create a vector of length 10 with values evenly distributed between 5 and 50
import numpy as np
v=np.linspace(5,50,10)
print(v)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [11]:
#create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15
import numpy as np
v=np.arange(0,21)
print("original array")
print(v)
print("After changing the sign of the numbers in the range from 9 to 15")
v[(v >= 9) & (v <= 15)] *= -1
print(v)

original array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [18]:
#create a vector with values from 100 to 200 and change the sign of the numbers in the range from 150 to 200
import numpy as np
v=np.arange(100,201)
print("original array")
print(v)
print("After change the sign of the numbers in the range from 150 to 200")
v[(v >= 150)&(v <= 200)] *= -1
print(v)


original array
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]
After change the sign of the numbers in the range from 150 to 200
[ 100  101  102  103  104  105  106  107  108  109  110  111  112  113
  114  115  116  117  118  119  120  121  122  123  124  125  126  127
  128  129  130  131  132  133  134  135  136  137  138  139  140  141
  142  143  144  145  146  147  148  149 -150 -151 -152 -153 -154 -155
 -156 -157 -158 -159 -160 -161 -162 -163 -164 -165 -166 -167 -168 -169
 -170 -171 -172 -173 -174 -175 -176 -177 -178 -179 -180 -181 -182 -183
 -184 -185 -186 -187 -188 -189 -190 -191 -192 -193 -194 -195 -196 -197
 -198 -199 

In [28]:
#Create a vector of length 5 filled with arbitary integers from 0 to 10
import numpy as np
a=np.random.randint(0,11,5)
print("Vector of length 5 filled with arbitary integers from 0 to 10")
print(a)

Vector of length 5 filled with arbitary integers from 0 to 10
[0 5 2 6 3]


In [31]:
#Multiply the values of two given vectors
import numpy as np
a=np.array([7,3,9])
print("Vector-1")
print(a)
b=np.array([8,2,5])
print("Vector-2")
print(b)
result=a*b
print("Multiply the values of two given vectors")
print(result)

Vector-1
[7 3 9]
Vector-2
[8 2 5]
Multiply the values of two given vectors
[56  6 45]


In [32]:
#create a 3x4 matrix filled with values from 10 to 21
import numpy as np
a=np.arange(10,22).reshape((3,4))
print("The 3x4 matrix is:")
print(a)

The 3x4 matrix is:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [35]:
#Find the number of rows and columns of a given matrix
import numpy as np
a=np.arange(10,22).reshape((3,4))
print(a)
print("The number of rows and columns of a given matrix")
print(a.shape)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
The number of rows and columns of a given matrix
(3, 4)


In [38]:
#3X3 identity matrix
import numpy as np
a=np.identity(3)
print("the 3X3 matrix is:")
print(a)
#Another function
a=np.eye(3)
print("The 3x3 matrix is:")
print(a)

the 3X3 matrix is:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
The 3x3 matrix is:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
#create a 10x10 matrix in which the elements on the borders will be equal to 1 and inside 0
import numpy as np
a=np.ones((10,10))
a[1:-1,1:-1]=0
print("The 10x10 matrix is:")
print(a)

The 10x10 matrix is:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [41]:
#create a 10x10 matrix in which the elements on the borders will be equal to 0 and inside 1
import numpy as np
a=np.zeros((10,10))
a[1:-1,1:-1]=1
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [44]:
#Create a 5x5 zero matrix with elemenets on the main diagonal equal to 1,2,3,4,5
import numpy as np
a=np.diag([1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [50]:
#Create a 4x4 matrix in which 0 and 1 are staggered,withzeros on the main diagonal
import numpy as np
a=np.zeros((4,4))
a[::2,1::2]=1
a[1::2,::2]=1
print(a)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [54]:
#Create a 3x3x3 array filles with arbitary values
import numpy as np
a=np.random.random((3,3,3))
print(a)

[[[0.1744476  0.83274996 0.19470492]
  [0.06990403 0.39503851 0.7361737 ]
  [0.02367916 0.27405015 0.08014498]]

 [[0.72762068 0.39224082 0.72640946]
  [0.70263099 0.39847439 0.5395061 ]
  [0.02608827 0.44922765 0.59273277]]

 [[0.10581634 0.79965549 0.42698826]
  [0.43871718 0.64234964 0.77001683]
  [0.61245894 0.39572943 0.16574079]]]


In [56]:
#To compute sum of all elements,sum of each column and sum of each row of a given array
import numpy as np
x=np.array([[0,1],[2,3]])
print("original array")
print(x)
print("Sum of all elements i a row:")
print(np.sum(x,axis=1))
print("Sum of all coloums:")
print(np.sum(x,axis=0))

original array
[[0 1]
 [2 3]]
Sum of all elements i a row:
[1 5]
Sum of all coloums:
[2 4]


In [57]:
#To compute the inner product of two given vectors
import numpy as np
x=np.array([3,4])
y=np.array([5,6])
print("original array")
print(x)
print(y)
print("Inner product of two given vectors")
print(np.dot(x,y))

original array
[3 4]
[5 6]
Inner product of two given vectors
39


In [3]:
#Add a vector to each row of a given matrix
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,2,3])
print("original vector: ")
print(v)
print("Given matrix")
print(a)
result=np.empty_like(4)
for i in range(5):
    result[i,:]=a[i,:]+v
    print("after adding a vector to each row of a given matrix")
    print(result)


original vector: 
[1 2 3]
Given matrix
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

In [4]:
# Datetime Exercises
import numpy as np
print("March,2022")
print(np.arange('2022-03','2022-04',dtype='datetime64[D]'))

March,2022
['2022-03-01' '2022-03-02' '2022-03-03' '2022-03-04' '2022-03-05'
 '2022-03-06' '2022-03-07' '2022-03-08' '2022-03-09' '2022-03-10'
 '2022-03-11' '2022-03-12' '2022-03-13' '2022-03-14' '2022-03-15'
 '2022-03-16' '2022-03-17' '2022-03-18' '2022-03-19' '2022-03-20'
 '2022-03-21' '2022-03-22' '2022-03-23' '2022-03-24' '2022-03-25'
 '2022-03-26' '2022-03-27' '2022-03-28' '2022-03-29' '2022-03-30'
 '2022-03-31']


In [7]:
# To get the dates of yesterday,today and tommarow
import numpy as np
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print("Yesterday:",yesterday)
today=np.datetime64('today','D')
print("today is:",today)
tommarow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("tommarow:",tommarow)

Yesterday: 2022-06-28
today is: 2022-06-29
tommarow: 2022-06-30


In [12]:
#Count the number of days of specific month
import numpy as np
print("Number of days,February,2016:")
print(np.datetime64('2016-03-01')-np.datetime64('2016-02-01'))
print("Number of days,February,2016:")
print(np.datetime64('2017-03-01')-np.datetime64('2017-02-01'))
print("Number of days,February,2016:")
print(np.datetime64('2018-03-01')-np.datetime64('2018-02-01'))

Number of days,February,2016:
29 days
Number of days,February,2016:
28 days
Number of days,February,2016:
28 days


In [24]:
# Find the first monday in may 2017
import numpy as np
print("The first monday in may 2017 is:")
print(np.busday_offset('2017-05',0,roll='forward'))

The first monday in may 2017 is:
2017-05-01


In [25]:
# Finding last monday in june 2022
import numpy as np
print("The last monday in june 2022 is:")
print(np.busday_offset('2022-06',31,roll='forward'))

The last monday in june 2022 is:
2022-07-14
