In [1]:
#Creating 1-D Array
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
a.shape

(10,)

In [8]:
#a[9]
#Negative index
a[-3]

7

In [10]:
# Createing 2-D Array
import numpy as np
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
#Zeros
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#Ones
a=np.ones((4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
a=np.empty((4,5))
a

array([[8.48798316e-314, 1.37521659e-311, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.69119194e-306, 8.34447260e-308, 2.29179042e-312,
        1.60219306e-306, 6.23059726e-307],
       [1.06811422e-306, 3.56043054e-307, 1.37961641e-306,
        8.90071135e-308, 8.90108313e-307],
       [1.11261298e-306, 1.24611470e-306, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [20]:
a=np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
a=np.isidentity(3,3)
a

AttributeError: module 'numpy' has no attribute 'isidentity'

In [ ]:
()