In [1]:
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a.shape

(10,)

In [5]:
a[8]

8

In [6]:
a[-1]

9

In [4]:
import numpy as np
a=np.array([8,2,0,5])
print("original array")
print(a)
print("After sorting:")
b=print(np.sort(a))

original array
[8 2 0 5]
After sorting:
[0 2 5 8]


In [10]:
import numpy as np
a=np.array(["vandana","joshna","apparao","manoj","kamala"])
print(np.sort(a))

['apparao' 'joshna' 'kamala' 'manoj' 'vandana']


In [11]:
import numpy as np
a=np.array([[9,7,0],[4,19,1]])
print(np.sort(a))

[[ 0  7  9]
 [ 1  4 19]]


In [12]:
import numpy as np
a=np.array([1,2,3,4,5,6])
new_filt=a%2==0
b=a[new_filt]
print(new_filt)
print(b)

[False  True False  True False  True]
[2 4 6]
